apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: work-server
spec:
  destination:
    name: work-server
  precedence: 1
  route:
  - labels:
      version: latest
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: meeting-server
spec:
  destination:
    name: meeting-server
  precedence: 1
  route:
  - labels:
      version: latest
