apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: work-server
spec:
  destination:
    name: work-server
  precedence: 1
  route:
  - labels:
      version: "1.0"
    weight: 80
  - labels:
      version: "2.0"
    weight: 20
